name: Build Shadow Executor

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile Resource File
      run: rc resource.rc

    - name: Build Executor DLL
      run: cl /EHsc /LD Executor.cpp /Fe:Executor.dll /link user32.lib gdi32.lib comctl32.lib version.lib

    - name: Build Main EXE
      run: cl /EHsc main.cpp resource.res /Fe:ShadowExecutor.exe /link user32.lib gdi32.lib comctl32.lib version.lib /SUBSYSTEM:WINDOWS

    - name: Upload Executor DLL
      uses: actions/upload-artifact@v4
      with:
        name: Executor-DLL
        path: Executor.dll

    - name: Upload Main EXE
      uses: actions/upload-artifact@v4
      with:
        name: Shadow-Executor-EXE
        path: ShadowExecutor.exe
